### ISSUE TITLE
Settings not retained on restart of Joplin

### ISSUE THREAD

**Issue by jahoyne** [personalizedrefrigerator/joplin-plugin-extra-editor-settings#1]
Everything works as expected, put the settings are not preserved after a restart of Joplin.

Once the settings are re-entered it works as expected. 

<details>
<summary><b>Joplin Version and Plugins in use</b></summary>

Joplin 3.0.6 (prod, linux)

Client ID: 615c7880d02145c5a89371d6264bdcb9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Admonition markdown extension: 1.1.0
Backup: 1.4.1
CodeMirror 6 settings: 1.0.0
CodeMirror 6 snippets: 0.0.5
Conflict Resolution: 1.2.3
Copy Code Blocks: 1.1.0
Copy Universal Web Link: 0.1.0
Create and go to #tags and @notebooks: 1.3.7
Draw.io: 2.2.0
Embed Search: 2.0.0
Enhancement: 1.2.1
History Panel: 1.0.2
Home Note: 2.0.0
Hotfolder: 1.1.1
Inline tags: 1.3.0
Insert Date: 1.0.1
joplin-note-email: 1.0.5
joplin-plugin-TimelineRender: 1.0.2
Kminder Mindmap Joplin Plugin: 0.8.6
Markdown Prettier: 0.1.0
Markdown Table: Colorize: 1.2.0
Markdown Table: Sortable: 1.2.2
Markmap: 1.6.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Statistics: 1.0.4
Note Tabs: 1.4.0
Outline: 1.5.13
Paste Special: 1.1.2
Persistent Editor Layout: 2.2.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Quick Move: 1.1.0
Rich Markdown: 0.15.0
Spoilers: 1.0.6
Tagging: 1.0.3
Templates: 2.4.0
turnToChart: 1.9.3
VS-Code Style Note Search: 0.0.1
</details>

Thanks, for all your great work.

**Comment by personalizedrefrigerator** [comment]
Thank you for letting me know! 

This plugin stores settings in `settings.json`  in the profile directory (rather than in Joplin's database). This is done using the [SettingStorageType.File](https://joplinapp.org/api/references/plugin_api/enums/settingstorage.html#file) option.

I think I've had this happen 1-2 times, but not consistently. I suspect that a bug exists in loading/saving settings to the JSON file.

**Comment by personalizedrefrigerator** [comment]
Upstream issue: https://github.com/laurent22/joplin/issues/10381

**Comment by personalizedrefrigerator** [comment]
Upstream pull request: https://github.com/laurent22/joplin/pull/10458

**Comment by personalizedrefrigerator** [comment]
As in the CodeMirror 6 snippets plugin, this [should be fixed in Joplin v3.0.9](https://github.com/personalizedrefrigerator/joplin-plugin-codemirror-6-snippets/issues/2#issuecomment-2163805981).

**Comment by personalizedrefrigerator** [comment]
Joplin 3.0.x is now stable! I'm closing this as resolved.
