### ISSUE TITLE
change color of trailing spaces

### ISSUE THREAD

**Issue by tino926** [personalizedrefrigerator/joplin-plugin-extra-editor-settings#2]
hi, thanks for the convenient tool.

I want to know is there a method to modify the color of trailing spaces?

**Comment by personalizedrefrigerator** [comment]
Hi,

Is this on mobile or desktop? On mobile, this isn't currently supported (without another custom plugin :) ). On desktop, this should be possible with a [custom userchrome.css file](https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370).

**Comment by personalizedrefrigerator** [comment]
I'm closing this as resolved. Please let me know if I should re-open it!
