### ISSUE TITLE
Consider rendering `* * *` as a line in "Hide markdown" mode

### ISSUE THREAD

**Issue by laurent22** [personalizedrefrigerator/joplin-plugin-extra-editor-settings#7]
If not too complicated it would be good to render `* * *`, `---` and `___` as a line (HR)

**Comment by alexgoussev** [comment]
I think it would be better to have it like separate option.

**Comment by laurent22** [comment]
There's actually already an option hide/show Markdown characters. Or if you mean having an option to toggle each Markdown character, I think that would be overkill.

**Comment by personalizedrefrigerator** [comment]
This should be resolved in v1.8.0.
