### ISSUE TITLE
Align Markdown checkboxes with their plain text equivalent

### ISSUE THREAD

**Issue by laurent22** [personalizedrefrigerator/joplin-plugin-extra-editor-settings#8]
In "Hide markdown" mode, when a checkbox is rendered it has something like a 10px margin on the left, and because of this the rendered and non-rendered checkboxes don't align. And that can make it difficult to know to which level a particular checkbox belongs to.

I'm thinking that if the left of the checkbox and the left of the dash was aligned, it would make things a bit more intuitive.

<img width="236" alt="image" src="https://github.com/user-attachments/assets/0b1e4a4f-b9e9-4773-8e2c-df0bbc58707e" />

**Comment by personalizedrefrigerator** [comment]
I've noticed that lines shift significantly when I click to focus them (due to Markdown being shown). An alternative might be to keep Markdown on the same line hidden, when not near the cursor, though it may make sense to check what other apps do.

**Comment by personalizedrefrigerator** [comment]
This should be resolved in v1.8.0.
